ghostty-org/website

docs/config/index.mdx

Fixed incorrect config path for macOS.
When installed via DMG, config is in `~/Library/Application Support/com.mitchellh.ghostty`, not `~/Library/Application Support/ghostty`.

fix: path to config file on macOS

---

docs/help/terminfo.mdx

Mention a common but harmless warning from the infocomp/tic command for configuring terminfo on a remote server.
I had this with three different remote systems, and it appeared from other people on the Discord.

Can ignore: older tic versions may treat the description field as an alias

---

docs/install/binary.mdx

This adds documentation on how to install the AUR packages maintained by @gpanders.

docs(install/binary): add documentation on AUR packages

---

docs/install/binary.mdx

`brew` will install `ghostty` correctly without the `--cask` argument. Just `brew install ghostty`, it's cleaner.
(Thank you for ghostty).

Remove `--cask` from `brew install`.

---

docs/config/index.mdx

A space considered as a separator between CLI arguments.
This should make Copy&Paste easier.

Make path easy to copy & paste

---

src/layouts/root-layout/index.tsx

When using Darkreader, parts of the website render with bad color schemes and contrast ratios
Implement a `darkreader-lock` meta tag within `src/layouts/root-layout/index.tsx` so it exists globally across the site
Resolves #150

Implement darkreader lock

---

docs/features/theme.mdx

Remove unnecessary $ prefix from command code blocks for better user experience. This change allows users to directly copy-paste commands without having to manually remove the $ symbol.

remove dollar sign prefix from command block

---

src/components/navbar/Navbar.module.css

RE: #153.  It looks like in Safari mobile `vh` calculation includes the address bar.  Using `dvh` seems to fix this one.

Fix safari navbar overflow issue

---

docs/install/build.mdx

Distros such as Void Linux require `pkg-config` to detect `gtk4` and `libadwaita`.

mention pkg-config when building for linux

---

src/components/terminal/Terminal.module.css

The border radius of the adwaita terminal header bar is the same as its parent causing this gap. Subtracting the thickness of the border from the radius closes the gap.
before:
after:

close border gap on adwaita terminal header

---

docs/help/macos-tiling-wms.mdx

When using "floating" layout, new windows created using "cmd+n" didn't recognise tiling commands like "alt+l" or "alt+h" to move it front and back. Only the first window created was being controlled like other tiling windows. It may be because floating windows aren't part of tiling tree.
The same thing happened to me with Kitty and the following config makes it work like how other windows in the aerospace tree work.
Here is the config that can be a sane default
```toml
[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= [ "layout tiling" ]
```
Closes https://github.com/ghostty-org/website/issues/163

[Behaviour] macos-tiling-wms.mdx: change layout to "tiling" to make shortcuts consistent with other open windows in the window manager

---

docs/install/binary.mdx

* Move to alphabetical order under Linux heading
* Remove confusing wording about official/community since Ghostty's perspective and Arch's perspective on this (or any distro for that matter) use the same terms to mean different things.
* Simplify/clarify where the package is and how to get it.
* Stop promoting the AUR package as a better alternative to the official stable package, and don't promote a specific AUR helper instead linking to relevant Arch docs.
Fixes up remnants of #135, see also #141.

Overhaul Arch instructions

---

docs/install/binary.mdx

https://formulae.brew.sh/cask/ghostty#default
reverts #149 
the --cask is not needed per se, but specifies that ghostty is a cask, and not a regular package. i think it's best to keep consistency among formulae.brew.sh

fix: add info for brew installation for macos

---

docs/config/keybind/reference.mdx

Based on [#3518](https://github.com/ghostty-org/ghostty/issues/3518) I have added info regarding pane splitting in quick terminal. I hope this is ok. Please suggest any changes if required.
Thanks!

add split panes info on quick terminal

---

docs/config/index.mdx

This PR makes the following improvements to the documentation for the configuration file config:
- Explicitly states the file name as config, ensuring readers understand both the file name and its possible locations.
- Use `$HOME` to refer to the home directory,  instead of both `~` and `$HOME`
- Introduce a new header structure (XDG Configuration Path and macOS-specific Path) for better readability and a more organized presentation. IMHO this is formatted better than using a combination of numbered lists, and un-ordered sub-lists.

Refine Configuration File location doc

---

docs/config/reference.mdx
docs/help/terminfo.mdx
docs/install/binary.mdx
docs/install/build.mdx
src/lib/fetch-docs.ts
src/styles/globals.css

Disables auto detection of the syntax highlighting language, which was causing some weird highlighting in cases where it wasn't detected correctly. This also corrects/adds missing language names to code blocks in the documentation itself, and sets the highlighter options to work for all languages (nix, for example, wasn't being highlighted).

Improve syntax highlighting

---

docs/install/binary.mdx

The instructions for arch got split incorrectly when the Gentoo and Nix instructions were added. This moves the AUR recipe back where it belongs.

Fix Arch installation instructions binary.mdx

---

docs/install/binary.mdx

adds install instructions from fedora copr 
https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/

add fedora install documentation

---

src/components/generic-card/GenericCard.module.css
src/components/generic-card/index.tsx
src/components/grid-container/index.tsx
src/pages/404.tsx
src/pages/download/index.tsx
src/types/style.ts

hoists the `DownloadCard` component to it's own `GenericCard` component for future use. This component will probably be extended with the work on the Showcase page 
> [!NOTE]
> This is a recreation of #129 because GH did not like the transition from private > public repo 🥴 
To tackle #125, My plan is a "grid" of cards with an image, title and description (possibly a modal to open config etc). Instead of re-creating something, moving this card component made sense.
- Closes #129

feat(generic-card): make generic card from download card

---

src/layouts/root-layout/index.tsx

Resolves #189 
Basically, favicon paths were not set properly in `src/layouts/root-layout/index.tsx`, causing the favicon to only appear properly at `/`

Fix broken favicon paths

---

docs/install/binary.mdx

The `ghostty-git` install command contains a comment about installing `Ghostty tip`. I assume this is a typo and should be `Ghostty git`. However, none of the other installation methods have such a comment, so it might be better to remove it all together.

docs(binary): fix typo

---

src/components/animated-terminal/index.tsx

Fix for #211 
Assuming we were looking for a whole pause here, unlike the reduced motion approach of resetting to frame 20.

Fix: paused home screen animation on focused blurred

---

src/pages/index.tsx

Adds `aria-hidden={true}` to the `<section>` in `src/pages/index.tsx` to prevent screen readers from reading the content of the animated terminal out loud.

Add 'aria-hidden={true}' to <section> at /

---

src/components/animated-terminal/index.tsx
src/components/terminal/Terminal.module.css
src/pages/Home.module.css

Was poking around a bit on the code for the Ghostty website and came up with a few items that I figured I could improve/clean up.
Probably easiest to look at the commits in order, but I'll list out the changes here.
**1. macOS Traffic Light Fixes**
Noticed a bit of a horizontal vs vertical padding imbalance with the macOS traffic light icons, so made a small tweak there
| BEFORE | AFTER |
| - | - |
| ![CleanShot 2024-12-29 at 23 29 25](https://github.com/user-attachments/assets/e00ed58f-8210-4e64-9419-06ff2c1ec4b0) | ![CleanShot 2024-12-29 at 23 29 08](https://github.com/user-attachments/assets/2426059d-6707-4612-9193-538616c2f28c) |
**2. Refactored Animation Loop Code**
Before the code was using setInterval which doesn't necessarily sync well with your monitor's screen updates. …

Misc Website Polish

---

docs/install/build.mdx

Adds build dependencies for Gentoo at [/docs/install/build](https://ghostty.org/docs/install/build)

Add build deps for Gentoo

---

src/components/animated-terminal/index.tsx
src/components/terminal/Terminal.module.css
src/pages/Home.module.css

This is a re-do of #216 due to a bug on iOS where the page wasn't focused on load.
This PR is exactly the same as before except now we use visibilityState on page load to determine animation state instead of focus state.

Misc Website Polish (v2)

---

src/components/terminal/Terminal.module.css
src/components/terminal/index.tsx

When the fix was applied for screen readers we triggered an error because the container of the terminal interface had a tab index, which it really shouldn't since there's nothing to interact with.
I've removed this tab index and also made the quick change to force the various header bar states to not have a toggle on hover since 1. it's a bit distracting and 2. sort of unnecessary.
This is what the error looked like:
This also has the nice side effect as a single tab action takes us directly to the download button.
Also it looks like there were some prettier changes that tweaked parts of the file.

Bug Fix: Fix aria-hidden error

---

Dockerfile

Fixed Docker warnings by switching stage name to lowercase and updating the CMD syntax. Docker was complaining about our uppercase stage name and the old shell-style CMD format, so I updated both to follow their recommended practices.

Fix Dockerfile: Update stage name casing and CMD syntax

---

src/components/sidecar/index.tsx

Bit of a pet peeve issue here, but when scrolling through longer sections, the sidecar will sometimes lose focus on what article is currently active.
[Screencast_20241230_102045.webm](https://github.com/user-attachments/assets/5f2d3d6c-b84c-4c32-bf44-5a599cf9a498)
This should keep at least *something* focused, which makes quickly scrolling through the docs less disorienting.
[Screencast_20241230_102155.webm](https://github.com/user-attachments/assets/bf563de3-e14c-49c2-802e-10373d36d0b8)

Fix: No highlighted sidecar items when scrolling through long articles

---

docs/install/binary.mdx

https://github.com/mkasberg/ghostty-ubuntu
Ubuntu is still one of the most popular Linux distributions, and I want to make it easier for everyone to install Ghostty on Ubuntu. Getting official Ubuntu packages (perhaps even PPAs) will take some time because Ubuntu still does not have official zig packages. But we can build a .deb on GitHub Actions and make it available to download on GitHub. That's the approach I'm taking in the above repo, which will hopefully be a good interim solution. (All of the usual caveats about unofficial packages still apply.)

Add a Link to .deb for Ubuntu

---

docs/install/build.mdx

On development Debian based distros the listed  dependencies does not meet the building requirements. In notes we mention  `gcc-multilib` which might not installed (not part of build-essential metapackage, nor required/recommended for libadwaita/libgtk).
E.g.: ghostty build successfully on Debian Bookworm, but not on Debian Testing without gcc-multilib

note: Mention gcc-multilib as possible dependency

---

docs/help/index.mdx
docs/help/macos-login-shells.mdx
docs/nav.json

Add a page under the help tab explaining why macos defaults to login shells, and how users should handle this discrepancy with their understanding of other unix systems.
This could probably use some style flavor, but all the content should be there and sourced; mainly from one stack overflow page that is quite verbose.

feat: add page explaining macOS login shell shenanigans

---

docs/help/macos-login-shells.mdx

Fixed a tiny typo caused by a word being broken with a newline.

Fix typo in macos-login-shells.mdx

---

docs/install/build.mdx

The current URL redirects to the GNOME GitLab login page. Not sure what the intention was, was it https://gitlab.gnome.org/GNOME/gtk/-/issues/6589#note_2072039 or https://gitlab.gnome.org/GNOME/gtk/-/issues/6589?

Fix URL typo in GNOME GitLab link in build.mdx

---

docs/install/binary.mdx

As seen in [OBS]( https://build.opensuse.org/request/show/1233711) the package from home:avindra was submitted to X11:terminals and therefore the repository path needs to be updated.

Update openSUSE repository path

---

docs/features/index.mdx

As discussed in https://github.com/ghostty-org/ghostty/issues/1442#issuecomment-2565793137,
this clarifies that RTL text is not supported, although rendering of
individual grapheme clusters from RTL scripts is done correctly.
cc @Flimm - is this language clearer?

Rephrase support for rendering RTL scripts

---

docs/help/terminfo.mdx

The brew prefix folder can be different, in my case:
```
❯ brew config
HOMEBREW_VERSION: 4.4.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: f84082963da8af8c9ccd6dffbe932eba457e2b78
Last commit: 4 days ago
Branch: stable
Core tap JSON: 03 Jan 21:11 UTC
Core cask tap JSON: 03 Jan 21:11 UTC
HOMEBREW_PREFIX: /usr/local
...
```
```
❯ ls -l /usr/local/opt/ncurses/bin/infocmp
-r-xr-xr-x@ 1 edu  admin  86616 Jan  3 22:12 /usr/local/opt/ncurses/bin/infocmp
~
❯ ls -l /opt/
total 0
``` 

Clarify OSX<sonoma instructions

---

docs/install/build.mdx

Package `wayland-protocols-devel` needs to be installed for the latest code to build, otherwise FTBFS.
Running the following fixes the build:
```
dnf install wayland-protocols-devel.noarch
```
NOTE: I haven't tested the Fedora Atomic package names.

package wayland-protocols-devel needed on CentOS Stream 9

---

docs/install/build.mdx

I updated the install commands for Arch and Debian/Ubuntu.
Debian: https://packages.debian.org/search?keywords=wayland-protocols
Ubuntu: https://launchpad.net/ubuntu/+source/wayland-protocols
Arch: https://archlinux.org/packages/extra/any/wayland-protocols/

Add wayland-protocols to required dependencies

---

docs/features/theme.mdx

`theme.mdx` presumably has missing hashtags in the front of hexadecimal codes. It was also missing the `cursor-text` option.

Fixed presumed typos in theme.mdx

---

src/layouts/nav-footer-layout/index.tsx

Currently, the year in the footer is 2024:
I've updated the copyright string so it will set the actual year every time the website builds.

Sets the current year for the copyright in the footer

---

docs/install/binary.mdx

If the package has dependencies that are not already installed, dpkg -i will fail, while apt  will automatically fetch and install the missing dependencies as well.  Also most users are more familiar with apt that they already use for installing packages and updates

Ubuntu | Replace dpkg with apt

---

docs/help/terminfo.mdx

I only found the terminfo FAQ section by going via GH Issue comments... I think just adding this error string is helpful; it is by far the most common error I have been seeing while testing.

Include "Error: opening terminal" for findability

---

docs/install/release-notes/index.mdx
docs/nav.json

This PR adds a page at https://ghostty.org/docs/install/release-notes to index all current and future releases.
This is done to partially complete https://github.com/ghostty-org/ghostty/issues/4730.

docs/install/release-notes: add index.mdx

---

docs/install/binary.mdx

* simplify `zypper` install to the official package
* Link to the `software.opensuse.org` entity

binary.mdx: update openSUSE Tumbleweed to official repo

---

docs/install/binary.mdx

Bundling Ghostty Terminal as a Universal AppImage, This will allow users to easily run Ghostty on various Linux distributions without the hassle of managing dependencies. Fixes [#4824](https://github.com/ghostty-org/ghostty/discussions/4824)
Repository Link: [Ghostty AppImage Repository](https://github.com/psadi/ghostty-appimage)
Benefits of the AppImage:
1. Universal Compatibility: Works on various Linux distributions.
1. No Installation Required: Just download and run!
1. Self-Contained: Includes all necessary dependencies.
Next is to publish the appimage to [AppImageHub](https://appimage.github.io/)
~~add support for other architectures (ARM etc)~~.
Edit: Arm/aarch64 appimage builds are now available.

Add link for Universal AppImage Distribution

---

Makefile
docs/config/keybind/reference.mdx
docs/config/reference.mdx

This PR adds a simple Makefile target for copying the `webdata` files into place from a Ghostty build directory (e.g. `/Users/akx/ghostty/zig-out` on my system). (Took some figuring out how the references are built (`zig build -Demit-webdata=true`).)
It then applies _some_ of the documentation updates since fe6c69263cdf2779e72014160970c3be31cbf1a2 with surgical `git add -p`s – namely, those that don't refer to newly added features.
When the next version of Ghostty is released, and the website should be updated with all the new fancy changes, one can just `make sync-webdata GHOSTTY_BUILD_DIR=../ghostty/zig-out; git add -u; git commit ...` away.
Related to #253.

Sync some documentation updates from app repo

---

docs/install/release-notes/1-1-0.mdx

Add https://github.com/ghostty-org/ghostty/pull/5285 to `1.1.0` release notes: Change default key bindings to capture full screen contents (`write_screen_file`)
This seems like a notable improvement (self-described but I think it should go somewhere :shrug:). Feel free to nit a more correct location in the list. I tried to just put it next to other keybinding improvements.

Add ghostty-org/ghostty#5285 to 1.1.0 release notes (Change default key bindings to capture full screen contents)

---

src/lib/nav-tree-to-breadcrumbs.ts

This pull request includes changes to the `navTreeToBreadcrumbs` function in the `src/lib/nav-tree-to-breadcrumbs.ts` file to improve error handling and breadcrumb generation.
Improvements to `navTreeToBreadcrumbs` function:
* Added a variable `currentSegment` to store the current URL segment being processed.
* Updated error handling to map remaining segments to breadcrumb items instead of throwing an error when the next node is undefined. This includes accumulating the path and creating breadcrumb objects with the segment name and full slug path.
#286

fix: enable rendering of docs page, exclude from nav tree

---

docs/config/keybind/index.mdx

docs: Fix "performable" header

---

docs/install/release-notes/index.mdx

I noticed the Release Notes "Overview" page does not include an entry for `1.1.2`.  Just a simple PR to add that to remain consistent with previous iterations.

add 1.1.2 release entry & link

---

docs/install/build.mdx

Related:
https://github.com/ghostty-org/ghostty/discussions/5967
I suggest that this be merged now, since most people looking for building from source would use the latest commit.

docs: update linux build instructions

---

bin/video-to-terminal/video-to-terminal.sh

- color distance and luminance calculations consolidated from multiple `bc` statements into relatively faster single `awk` (faster) statement
- Replaced `convert` with `magick` to remove deprecation warnings
- Replaced `identify` with `magick identify` to be more explicit

Speed up video-to-terminal.sh script

---

docs/help/terminfo.mdx

Make the ncurses info on the terminfo slightly more helpful by supplying the version number.
Reference:
- https://lists.gnu.org/archive/html/bug-ncurses/2024-12/msg00043.html
- https://lists.gnu.org/archive/html/bug-ncurses/2025-02/msg00045.html

terminfo: specific ncurses info

---

docs/vt/concepts/cursor.mdx

This change the link from [this](https://ghostty.org/docs/concepts/screen) that is a 404 to [this](https://ghostty.org/docs/vt/concepts/screen) that is the placeholder todo screen page.

Fix broken link to screen

---

docs/help/terminfo.mdx

Something that seems to be pretty common is for people to run the `infocmp` command in a terminal emulator other than Ghostty, presumably as a stop-gap until they fix their terminfo.  This makes the command do absolutely nothing and has been the source of confusion on multiple occassions.
`ghostty` is used instead of `xterm-ghostty` as ncurses doesn't ship `xterm-ghostty` and both seem to generate the same output (apart from the comment at the top).

Explicitly specify `ghostty` in the infocmp command

---

docs/config/keybind/index.mdx

I suggest adding a hint on how to find the default keybindings to the docs.
I personally first went to [keybindings overview](https://ghostty.org/docs/config/keybind) and didn’t find them there.
Using a search engine you can find this: https://gist.github.com/hensg/43bc71c21d1f79385892352a390aa2ca 
See the comments there for more people describing having the same problems with finding the default keybindings.
I read CONTRIBUTING.md and take the risk as it seems to be a pattern that people do not find this cli command.
There is also already a discussion which would be closed by this PR: https://github.com/ghostty-org/ghostty/discussions/4517

Add `+list-keybinds` note for people searching for default keybindings

---

docs/install/binary.mdx

The current documentation leads to create a `.repo` file with the content:
```ini
[copr:copr.fedorainfracloud.org:pgdev:ghostty]
name=Copr repo for Ghostty owned by pgdev
baseurl=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/fedora--/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1' | sudo tee /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pgdev:ghostty.repo > /dev/null
```
Note that the correct `baseurl` must be 
```ini
baseurl=https://download.copr.fedorainfracloud.org/results/pgdev/ghostty/fedora-$releasever-$basearch/
```
The double quotes evaluate the `$releasever` and `$basearch` values which is normally empty. This variables are used …

fix: Change quotes for rpm-ostree installation documentation

---

docs/install/binary.mdx

Added information about the new downstream (maintainer) org in installation steps.
*Note: i will be maintaing the appimage as usual, just that its under an org now*

Update binary.mdx for appimages

---

docs/install/build.mdx

Without this, the following error shows:
```
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
```

fix: include libxml2-utils to debian dependencies

---

docs/vt/control/lf.mdx
docs/vt/csi/decslrm.mdx
docs/vt/csi/decstbm.mdx
docs/vt/csi/ed.mdx
docs/vt/csi/el.mdx
docs/vt/csi/su.mdx
docs/vt/csi/vpr.mdx
docs/vt/esc/ris.mdx

This is like #317, but I did a more thorough search for broken links.
I found these two links to pages that do not yet exist. I'm not sure if I should delete the href and replace it with `#TODO` or leave it as is:
- `/vt/modes/origin` (maybe this should be `docs/vt/modes/origin`, with the `docs/` at the beginning) on `docs/vt/esc/decsc.mdx` and `docs/vt/csi/cht.mdx`.
- `/docs/vt/csi/hts` on `docs/vt/csi/cht.mdx` and `docs/vt/csi/cbt.mdx`.

docs: fix relative links

---

docs/help/terminfo.mdx

Quoting myself from #325:
> `ghostty` is used instead of `xterm-ghostty` as ncurses doesn't ship `xterm-ghostty` and both seem to generate the same output (apart from the comment at the top).
That reasoning appears to have backfired: recently, in [a Discord #help post], the command did not work for somebody because their system had both ncurses' `ghostty` and Ghostty's `xterm-ghostty` installed, resulting in `ghostty` being copied over when `xterm-ghostty` was expected.  I had thought ncurses had a fallback for `xterm-ghostty` specified despite their reluctance to name the terminfo file `xterm-ghostty`, but [its database doesn't seem to do that], so their `ghostty` terminfo doesn't actually work because the default `$TERM` value is `xterm-ghostty`.
I'm not sure what to do about this, but …

Specify using `xterm-ghostty` instead of `ghostty` in the infocmp command

---

docs/install/build.mdx

I needed to add `gtk4-layer-shell-devel` dependency building on Fedora 42.

docs: add missing fedora dependency

---

docs/install/binary.mdx

Current COPR is still on 1.1.2 and it seems like the author is not responding to issues [^1].
I'm proposing to start suggesting a better maintained package by @scottames.
I'm not suggesting changes to Atomic desktops as I'm not familiar with package compatibility there (maybe it's trivial).
[^1]:https://gitlab.com/pgill/ghostty-rpm/-/issues/4

fedora: change suggested COPR

---

docs/install/build.mdx

It seems like without this package, ghostty will not build after https://github.com/ghostty-org/ghostty/pull/6706.
However, it seems like libgtk4-layer-shell-dev is only available in Ubuntu 24.10+ and Debian trixie+. I've only tried this on a Ubuntu 25.04 machine tho.

update libgtk4-layer-shell-dev for ubuntu build instructions

---

docs/vt/csi/cbt.mdx
docs/vt/csi/cht.mdx
docs/vt/csi/dsr.mdx
docs/vt/esc/decsc.mdx

There are a few pages (4) that link to 2 docs pages that are `#TODO` (they are missing now). So I replace the `href` with a `#TODO` as suggested [here](https://github.com/ghostty-org/website/pull/318#issuecomment-2825472935) to avoid 404 errors.

docs: remove links to missing pages and replace with '#TODO'

---

docs/install/binary.mdx

Ghostty is also in nixpkgs stable channel nowadays, so this generalizes the description from `nixpkgs unstable` to `nixpkgs`

docs: generalize nixpkgs unstable to nixpkgs

---

docs/install/build.mdx

While building ghostty for RHEL-based distros I noticed that the `gtk-adwaita` build flag does not exist anymore.
Seems this is the case since https://github.com/ghostty-org/ghostty/pull/5749

tip: update libadwaita build dependency notice

---

docs/install/release-notes/1-2-0.mdx

Adds highlights relating to renderer and font changes, several TODOs in there still, but the key points are outlined.
(Also I fixed some typos while I was in the file lol)

Add renderer and font highlights to 1.2.0 release notes

---

docs/install/release-notes/1-2-0.mdx

The release notes say 10 seconds, the config reference and code both say 5.

Fix undo-timeout default in 1.2.0 release notes

---

docs/linux/systemd.mdx

Hi, while reading the [Systemd and D-Bus Integration](https://ghostty.org/docs/linux/systemd), I found few typos that I fixed.
Here are the changes:
**Before**
```text
PREFiX (i is lowercase)
Hyperland (e)
app-com.mitchell.ghostty-debug.service (missing h)
You can tell Ghostty to reload it's config ... (it's)
This process ensures that any startup delayed caused by GTK ... (delayed)
```
**After**
```text
PREFIX
Hyprland
app-com.mitchellh.ghostty-debug.service
You can tell Ghostty to reload its config
This process ensures that any startup delay caused by GTK ...
```

Fixed typos in systemd.mdx
