- src/styles/globals.css
|BEFORE|AFTER|
|---|---|
|![image](https://github.com/user-attachments/assets/0e41f0ce-ce8a-4398-ade8-c62a4b177e88)|![image](https://github.com/user-attachments/assets/bf1a413f-66e6-4b80-bfea-b74f7dc007e3)|
> Set scrollbar color to dark

- src/components/codeblock/CodeBlock.module.css
- src/components/codeblock/index.tsx
> add copy button to code blocks

- docs/install/binary.mdx
- src/pages/download/DownloadPage.module.css
- src/pages/download/index.tsx
- Add in section for homebrew under macOS section
- Add button for package manager instructions for macOS
- copy over styling from linux section
> feat: Add in section for homebrew

- src/components/codeblock/CodeBlock.module.css
https://github.com/ghostty-org/website/pull/140#issuecomment-2563131285
> show code block copy button only on hover

- package-lock.json
- package.json
- src/components/custom-mdx/index.tsx
- src/components/jumplink-header/index.tsx
- src/components/sidecar/index.tsx
- src/lib/fetch-docs.ts
- src/lib/use-store.ts
- src/pages/docs/[...path]/index.tsx
Less re-renders wohoo!
Before.
https://github.com/user-attachments/assets/e8d46a6b-87cb-499d-8df3-488b26291823
After.
https://github.com/user-attachments/assets/1a5eb075-9fa6-439e-9ba5-9e7dc56ba2c0
> feat: manage state with zustand

- src/components/footer/Footer.module.css
- src/components/navbar/Navbar.module.css
- src/pages/docs/[...path]/DocsPage.module.css
- src/pages/docs/[...path]/index.tsx
- src/styles/globals.css
Closes #63
if `@media print` is active
- remove the navbar, footer, sidebar
- switch to a light theme
- remove `max-width` on the content
> add print stylesheet

- src/pages/download/DownloadPage.module.css
Removes some CSS which is no longer in use as of #166
> Removes dead CSS

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
Discussed in the Discord with @BrandonRomano
> Create issue templates

- .github/ISSUE_TEMPLATE/config.yml
I forgot to add `about` in the config.yml, leading to somewhat broken CI.
> Fix config.yml

- docs/install/build.mdx
Added Solus dependencies to build ghostty. Verified build using these.
> Add Solus depends to build 

- docs/install/pre.mdx
Everything is in the title. Please tell me if I made any grammar mistake, English isn't my first language.
> add mention of the Tip version being available in Homebrew

- docs/install/build.mdx
Added opensuse tumbleweed to build. Verified
> Add Opensuse tumbleweed to build

- docs/install/binary.mdx
- docs/vt/concepts/cursor.mdx
- docs/vt/concepts/sequences.mdx
Adds missing commas in `docs/install/binary.mdx`, `docs/vt/concepts/cursor.mdx`, and `docs/vt/concepts/sequences.mdx`.
> Add missing commas

- docs/vt/concepts/sequences.mdx
There are more than 5 types of control sequences. Define each and
provide a simple example or syntax for each.
> vt: add documentation for all control sequence types

- docs/help/macos-tiling-wms.mdx
"layout tiling" doesn't seem to address the issue for a number of users. Added alternative workaround and behavior notes based on prior community discussions.
feel free to adjust the wording as you see fit!
> [edit] macos-tiling-wms.mdx: add alternative Aerospace workaround

- docs/help/terminfo.mdx
This change was approved in ghostty-org/ghostty#4562.
> terminfo: Mention another error during ssh

- src/pages/download/DownloadPage.module.css
- src/pages/download/index.tsx
Adjustments of #252 -- I didn't have permissions to push to that remote and I needed to make a tweak.
Fixes #242
> Link to Release Notes from Download Page

- docs/install/build.mdx
Realized that some packages were missing from suse installs and made it easier for solus.
> fix) suse and solus depends

- src/components/terminal/Terminal.module.css
- src/components/terminal/index.tsx
Also removed a bunch of things from when we had hover animations
> terminal(adw): move new tab button to the left, cleanup

- docs/install/build.mdx
> add void depends

- docs/install/release-notes/1-1-0.mdx
Fix typo: Bluetooh -> Bluetooth
> Update 1-1-0.mdx Fix typo: Bluetooh -> Bluetooth

- docs/install/binary.mdx
Instead of opening an editor and then pasting the repo content in, this will just create the repo file with the contents using one command.
> Better Fedora atomic documentation 📃

- docs/nav.json
- docs/vt/csi/decscusr.mdx
- docs/vt/reference.mdx
It is a CSI sequence not a plain escape sequence.
> Correct documentation of DECSCUSR

- docs/install/binary.mdx
Follow-up to #341 (thanks @slagiewka!)
Updates the Fedora Atomic instructions to match #341.
> docs(install/binary): update fedora atomic to reflect #341

- src/components/nav-tree/NavTree.module.css
Issue #344 
Font-family will be consistent across the website.
Looks like HTML Button will be using browser stylesheet if not defined directly.
> fix: wrong font rendering on nav-tree

- src/components/jumplink-header/index.tsx
- src/lib/fetch-docs.ts
Fixes #381
See https://website-git-fix-sidebar-ghostty.vercel.app/docs/install/build
> Ensure Header IDs are unique
